### ISSUE TITLE
Cannot find module eslint-config-airbnb-base/rules/best-practices after upgrade to 14.0.0

### ISSUE THREAD

**Issue by dfernandez79** [iamturns/eslint-config-airbnb-typescript#241]
## Problem
After upgrading from `12.3.1` to `14.0.0` I start getting this error (I tried the upgrade in two different projects with the same error):

```
Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Cannot read config file: /project/node_modules/eslint-config-airbnb-typescript/lib/shared.js
Error: Cannot find module 'eslint-config-airbnb-base/rules/best-practices'
Require stack:
- /project/node_modules/eslint-config-airbnb-typescript/lib/shared.js
- /project/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /project/node_modules/@eslint/eslintrc/lib/index.js
- /project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /project/node_modules/eslint/lib/eslint/eslint.js
- /project/node_modules/eslint/lib/eslint/index.js
- /project/node_modules/eslint/lib/cli.js
- /project/node_modules/eslint/bin/eslint.js
Referenced from: /project/node_modules/eslint-config-airbnb-typescript/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/project/node_modules/eslint-config-airbnb-typescript/lib/shared.js:2:43)
    at Module._compile (/project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
```

## Dependencies:
- `@typescript-eslint/parser: ^4.29.3`
- `@typescript-eslint/eslint-plugin: ^4.29.3`
- `eslint: ^7.32.0`

**Comment by sjoqvist** [comment]
I had the same issue, but I found this instruction under ["Breaking Changes" for version 13.0.0](https://github.com/iamturns/eslint-config-airbnb-typescript/releases/tag/v13.0.0):
* Install `eslint-config-airbnb` (or `eslint-config-airbnb-base`) and `@typescript-eslint/parser` as dependencies. Follow the updated README.md file.

Following the instruction solved the problem for me.

**Comment by Joshuabaker2** [comment]
I had to install both `eslint-config-airbnb` and also `eslint-config-airbnb-base` to get it to work for me.

**Comment by eps1lon** [comment]
> Install eslint-config-airbnb (or eslint-config-airbnb-base) and @typescript-eslint/parser as dependencies. Follow the updated README.md file.

This implies that `eslint-config-airbnb-base` is optional. But it's required as of 14.x. Or rather it's unclear when one needs to install it.

Either `eslint-config-airbnb` needs to declare `eslint-config-airbnb-base` as direct dependency (`dependencies`) or a (optional) peer dependency (`peerDependencies`). Right now the dependency is implicit and I'm pretty sure new package managers such as yarn v2 complain about these types of dependencies.
