### ISSUE TITLE
Error since bumping to 7.0.0

### ISSUE THREAD

**Issue by santaclauze** [iamturns/eslint-config-airbnb-typescript#66]
Hi,

First of all thanks for the package! 

We are using this and have just bumped to 2.19.0 and ahve the following error when eslinting:

```
$ NODE_ENV=development eslint src --ext .js,.jsx,.ts,.tsx
TypeError: sourceCode.isSpaceBetween is not a function
Occurred while linting /Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/src/apollo/apollo.ts:1
    at validateCommaSpacing (/Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:88:44)
    at /Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:132:21
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:126:35)
    at /Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/eslint/lib/util/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/Users/alexander.janet/workspace/github.com/Shuttlerock/spielberg-ui/node_modules/eslint/lib/util/node-event-generator.js:303:14)
error Command failed with exit code 2.
```

I followed the breaking change [migration](https://github.com/iamturns/eslint-config-airbnb-typescript/pull/63).

Any idea if this is on your side?

**Comment by iamturns** [comment]
Hey @santaclauze sorry to hear about this,

I won't be at a computer for a few days (currently on my phone), so I won't be able to investigate for a little while.

In the meantime, could you check you're on the latest versions of ESLint and all its associated plugins?

And does the same error occur when linting every file? Or only when attempting to lint part of your code?

**Comment by santaclauze** [comment]
@iamturns  all good, thanks for answering even while being away.

Yes, our eslint was oudated. We have automatic bumps so I expected it to be up to date, my bad.

Thanks for the prompt response ;) Enjoy your time off :)

**Comment by iamturns** [comment]
Glad it's resolved, cheers 👍
